/**
 * Property Lease Onboarding Workflow — 12-step sequence.
 *
 * This file defines the step sequence, automation levels, and checkpoint types
 * for the property lease onboarding workflow. It is consumed by:
 * - WorkflowProgressTracker component
 * - WorkflowHistoryPanel component
 * - ScreenGate (determines which screens are active at each step)
 * - agents/orchestrator/workflowOrchestrator.ts
 *
 * ARCHITECTURE NOTE: This is a frontend-side definition of the workflow
 * sequence. The backend workflow engine reads its own copy. These must
 * stay in sync. When the backend sequence changes, update this file.
 */
import type { WorkflowSequence } from '../../types/workflows/WorkflowStep'

export const PROPERTY_LEASE_ONBOARDING_WORKFLOW_ID = 'property_lease_onboarding_v1'

export const propertyLeaseOnboardingWorkflow: WorkflowSequence = {
  id: PROPERTY_LEASE_ONBOARDING_WORKFLOW_ID,
  onStepFailure: 'pause_and_notify',
  steps: [
    {
      stepId: 'step_01_document_upload',
      label: 'Document Upload',
      operation: 'uploadDocument',
      inputSource: 'user',
      automationLevel: 'manual',
      retryable: false,
      maxRetries: null,
      pollingInterval: null,
      successCondition: 'document.processingStatus === "uploaded"',
      checkpointType: null,
      humanActionRequired: true,
      timeoutHours: 72,
    },
    {
      stepId: 'step_02_ocr_processing',
      label: 'OCR Processing',
      operation: 'initiateOcr',
      inputSource: 'step_01_document_upload',
      automationLevel: 'all',
      retryable: true,
      maxRetries: 3,
      pollingInterval: 5000,
      successCondition: 'ocrResult.status === "completed"',
      checkpointType: null,
      humanActionRequired: false,
      timeoutHours: 2,
    },
    {
      stepId: 'step_03_field_extraction',
      label: 'Field Extraction',
      operation: 'extractFields',
      inputSource: 'step_02_ocr_processing',
      automationLevel: 'all',
      retryable: true,
      maxRetries: 2,
      pollingInterval: null,
      successCondition: 'extractionResult.status === "completed"',
      checkpointType: null,
      humanActionRequired: false,
      timeoutHours: 1,
    },
    {
      stepId: 'step_04_extraction_review',
      label: 'Extraction Review',
      operation: 'reviewExtraction',
      inputSource: 'step_03_field_extraction',
      automationLevel: 'collaborative | manual',
      retryable: false,
      maxRetries: null,
      pollingInterval: null,
      successCondition: 'extractionResult.isConfirmed === true',
      checkpointType: 'extraction_review',
      humanActionRequired: true,
      timeoutHours: 48,
    },
    {
      stepId: 'step_05_data_validation',
      label: 'Data Validation',
      operation: 'validateLeaseData',
      inputSource: 'step_04_extraction_review',
      automationLevel: 'all',
      retryable: true,
      maxRetries: 1,
      pollingInterval: null,
      successCondition: 'validationResult.isValid === true',
      checkpointType: null,
      humanActionRequired: false,
      timeoutHours: 0.5,
    },
    {
      stepId: 'step_06_survey_dispatch',
      label: 'Survey Dispatch',
      operation: 'dispatchSurvey',
      inputSource: 'step_05_data_validation',
      automationLevel: 'all',
      retryable: true,
      maxRetries: 2,
      pollingInterval: null,
      successCondition: 'survey.status === "active"',
      checkpointType: null,
      humanActionRequired: false,
      timeoutHours: 1,
    },
    {
      stepId: 'step_07_survey_completion',
      label: 'Survey Completion',
      operation: 'awaitSurveyResponse',
      inputSource: 'step_06_survey_dispatch',
      automationLevel: 'manual',
      retryable: false,
      maxRetries: null,
      pollingInterval: null,
      successCondition: 'surveyResponse.status === "submitted"',
      checkpointType: null,
      humanActionRequired: true,
      timeoutHours: 168,
    },
    {
      stepId: 'step_08_reassessment_analysis',
      label: 'Reassessment Analysis',
      operation: 'analyzeReassessment',
      inputSource: 'step_07_survey_completion',
      automationLevel: 'all',
      retryable: true,
      maxRetries: 2,
      pollingInterval: null,
      successCondition: 'reassessment.agentRecommendation !== null',
      checkpointType: null,
      humanActionRequired: false,
      timeoutHours: 4,
    },
    {
      stepId: 'step_09_reassessment_review',
      label: 'Reassessment Review',
      operation: 'reviewReassessment',
      inputSource: 'step_08_reassessment_analysis',
      automationLevel: 'collaborative | manual',
      retryable: false,
      maxRetries: null,
      pollingInterval: null,
      successCondition: 'reassessment.humanDecision !== null',
      checkpointType: 'reassessment_review',
      humanActionRequired: true,
      timeoutHours: 72,
    },
    {
      stepId: 'step_10_contract_preparation',
      label: 'Contract Preparation',
      operation: 'prepareContract',
      inputSource: 'step_09_reassessment_review',
      automationLevel: 'all',
      retryable: true,
      maxRetries: 2,
      pollingInterval: null,
      successCondition: 'contract.status === "pending_approval"',
      checkpointType: null,
      humanActionRequired: false,
      timeoutHours: 2,
    },
    {
      stepId: 'step_11_approval',
      label: 'Approval',
      operation: 'approveContract',
      inputSource: 'step_10_contract_preparation',
      automationLevel: 'manual',
      retryable: false,
      maxRetries: null,
      pollingInterval: null,
      successCondition: 'contract.status === "approved"',
      checkpointType: 'final_approval',
      humanActionRequired: true,
      timeoutHours: 96,
    },
    {
      stepId: 'step_12_archival',
      label: 'Archival',
      operation: 'archiveContract',
      inputSource: 'step_11_approval',
      automationLevel: 'all',
      retryable: true,
      maxRetries: 2,
      pollingInterval: null,
      successCondition: 'contract.status === "archived"',
      checkpointType: null,
      humanActionRequired: false,
      timeoutHours: 1,
    },
  ],
}
